### ISSUE TITLE
No duplicate check for new property

### ISSUE THREAD

**Issue by Wxy2003-xy** [AY2425S1-CS2103-F09-2/tp#104]
Command:
addProperty 11 address/12 reservouir road town/Bedok type/condo size/0.2 bed/1 bath/0 price/100
addProperty 11 address/12 reservouir road town/Bedok type/condo size/0.2 bed/1 bath/0 price/100

Result:
Same properties displayed twice 

Properties with all fields being identical are allowed to be added to the same person.

**Comment by jinnsuke** [comment]
fixed
