### ISSUE TITLE
[PE-D][Tester B] Manual testing in Developer Guide is not populated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103-F09-2/tp#177]
Original documentations are still in there

![image.png](https://raw.githubusercontent.com/hanscau/ped/main/files/0fa3b8ab-c109-45e9-aded-804acc4dd342.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: hanscau/ped#12

**Comment by jinnsuke** [comment]
Done
